### PR TITLE
README.rst: Absolute URLs to images

### PR DESCRIPTION
**Pull request by msabramo**
This should let the images render on PyPI.

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Thanks, merged in: https://github.com/jonathanslenders/ptpython/commit/c47dad1791b4e0030531742b2e4fa100acf9ca3a

Do I have to push again to Pypi, or will it get picked up automatically?

**Comment by msabramo** [comment]
Try `python setup.py register` to update the metadata on PyPI.

**Comment by jonathanslenders** [comment]
Looks like everything is gone now: https://pypi.python.org/pypi/ptpython

**Comment by msabramo** [comment]
That's because of this line - https://github.com/jonathanslenders/ptpython/blob/master/setup.py#L11

I can send a PR to fix that.

**Comment by jonathanslenders** [comment]
Ok, I'll fix it. Thanks!

**Comment by msabramo** [comment]
See https://github.com/jonathanslenders/ptpython/pull/8

**Comment by msabramo** [comment]
Fixed by c47dad1

**Comment by jonathanslenders** [comment]
The description is back, but images are not yet visible: https://pypi.python.org/pypi/ptpython

**Comment by msabramo** [comment]
Images not showing up on PyPI fixed by https://github.com/jonathanslenders/ptpython/pull/10

**Pull request closed without merging**
