### PR TITLE
Preference implementation

### PR DESCRIPTION
**Pull request by scottsievert**
## Issue
I wanted ptpython to have certain value on startup. For example, I always wanted to show the docstring and not change it each time.

## Solution
This fork reads ~/.ptpython for new startup values. This file does not have to exist, and not every option has to be included. This fork keeps the default values and only overwrites the default value if it finds a new value in this file.

The ~/.ptpython follows the [INI file format], going off Python's [ConfigParser](https://docs.python.org/3/library/configparser.html) (which plays nice with 2to3). For example, here is a file that loads the default values:

```lisp
;  FILE: ~/.ptpython

[startup]
complete while typing : True
paste mode            : False
show signature        : True
show docstring        : False
show linenumbers      : True
```

But having *all* the preferences is not nescessary; my ~/.ptpython file is

```
[startup]
show docstring : True
```

If there are errors in parsing, it produces a helpful message (tested with comments, headers):

```shell
ConfigParser.ParsingError: File contains parsing errors: /Users/scott/.ptpython
	[line  2]: 'this is not a comment!\n'
```

I have included similar documentation in the `PythonCLISettings` docstring.

## Further work
* nosetesting. The basic testing I did passed.
* Allow default keymaps to be changed

[ConfigParser]:https://docs.python.org/3/library/configparser.html
[INI file format]:https://en.wikipedia.org/wiki/INI_file

### CODE REVIEW

**Comment by ryneeverett** [comment]
Sweet.

**Comment by jonathanslenders** [comment]
Hi @scottsievert  Thanks a lot for spending the time on this pull request.

I'm however not yet going to merge it straight away. Recently I made ``pyvim`` configurable, and probably I'd like to have the same approach here, because that gives a lot more flexibility. (Adding custom key bindings, color schemes, macros, etc...)

So, please allow me some more time, to do some changes, and hopefully we have that soon.

Jonathan

**Comment by scottsievert** [comment]
Sounds good. What's the ETA of that?

**Comment by jonathanslenders** [comment]
Hi @scottsievert:

Preferences were implemented: https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py

(Sorry about not using your pull request, it was too different from the approach I wanted to take.)
Next step is to allow changing the color scheme dynamically..

Jonathan

**Comment by scottsievert** [comment]
No worries -- I'm just glad it got implemented!

**Pull request closed without merging**
