### PR TITLE
setup.py: Set long_description from README.rst

### PR DESCRIPTION
**Pull request by msabramo**
```
[marca@marca-mac2 ptpython]$ python setup.py egg_info
...
writing ptpython.egg-info/PKG-INFO
...
[marca@marca-mac2 ptpython]$ cat ptpython.egg-info/PKG-INFO
Metadata-Version: 1.0
Name: ptpython
Version: 0.3
Summary: Python REPL build on top of prompt_toolkit
Home-page: https://github.com/jonathanslenders/ptpython
Author: Jonathan Slenders
Author-email: UNKNOWN
License: UNKNOWN
Description: ptpython: a better Python REPL
        ==============================

        ``ptpython`` is an advanced Python REPL built on top of the `prompt_toolkit
        <http://github.com/jonathanslenders/python-prompt-toolkit>`_ library.
...
```

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Merged in: https://github.com/jonathanslenders/ptpython/commit/8dedd7e0872494be21e9106310bda4394df63a9e

Thanks!

**Comment by jonathanslenders** [comment]
(I still have to upload this to Pypi. But I'll do that later. -- it also needs a new version of prompt-toolkit.)

**Comment by msabramo** [comment]
Cool! Try `python setup.py register` to update the metadata on PyPI and I think you'll get your description back.

**Comment by jonathanslenders** [comment]
Question. Could you also make a similar pull request for the prompt-toolkit library? (There we also have relative paths to images and an empty long_description.)

**Pull request closed without merging**
