### PR TITLE
README.rst: Change image URLs from blob to raw

### PR DESCRIPTION
**Pull request by msabramo**
so that they show up on PyPI.

### CODE REVIEW

**Comment by jonathanslenders** [comment]
There we are: https://pypi.python.org/pypi/ptpython :+1: 

Thanks!

Merge in: https://github.com/jonathanslenders/ptpython/commit/cba050ca986e8928ba941d8d8cd6beaf0b1884a6

**Comment by msabramo** [comment]
Nice!!!

**Comment by msabramo** [comment]
Now I need to start playing with all the features of ptpython. It looks awesome!!!

https://twitter.com/MSAbramo/status/559384448832008192

**Comment by jonathanslenders** [comment]
Have fun!!
And feel free to create a GitHub issue when you feel something can be improved.

**Pull request closed without merging**
